app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fallback:
    pattern: /{url}
    defaults: { _controller: AppBundle:Default:index, url: null }
    requirements:
        url: .*
